### ISSUE TITLE
Add Generic KCal Control for Qualcomm MSM Framebuffer

### ISSUE THREAD

**Issue by javelinanddart** [showp1984/KControl#14]
/sys/devices/virtual/graphics/fb0/kcal
and 
/sys/devices/virtual/graphics/fb1/kcal
and probably 
/sys/devices/virtual/graphics/fb2/kcal
as well if you're triple buffering
it contains 3 numbers, 255 255 255 stock
First Value is Red, Second Value is Green, Third Value is Blue

**Comment by showp1984** [comment]
Oops? This was still here? I switched everything to my own gitlab, so I didn't even notice =\

**Comment by javelinanddart** [comment]
It's all good - it's no longer really relevant to me. If it's relevant to any users, it'll be a small minority of them.
