### ISSUE TITLE
Crash in MPDecision section

### ISSUE THREAD

**Issue by sylaan** [showp1984/KControl#8]
If I click on the MPDecision thingy, I get to see the 4 core display for couple of seconds and then KControl crashes. Relevant logcat:

<pre>
I/de.bricked.kcontrol.MpdecisionSettings( 8555): Setting Light theme...
D/audio_hw_primary(  185): out_standby: enter: usecase(1: low-latency-playback)
W/dalvikvm( 8555): threadid=16: thread exiting with uncaught exception (group=0x4160f700)
E/AndroidRuntime( 8555): FATAL EXCEPTION: Thread-529
E/AndroidRuntime( 8555): java.lang.StringIndexOutOfBoundsException: length=0; index=0
E/AndroidRuntime( 8555):        at de.bricked.kcontrol.MpdecisionSettings.f(Unknown Source)
E/AndroidRuntime( 8555):        at de.bricked.kcontrol.ej.run(Unknown Source)
E/AndroidRuntime( 8555):        at java.lang.Thread.run(Thread.java:841)
W/ActivityManager(  644):   Force finishing activity de.bricked.kcontrol/.MpdecisionSettings
D/audio_hw_primary(  185): stop_output_stream: enter: usecase(1: low-latency-playback)
D/audio_hw_primary(  185): disable_audio_route: reset mixer path: low-latency-playback
D/audio_hw_primary(  185): disable_snd_device: snd_device(2: speaker)
D/audio_hw_primary(  185): stop_output_stream: exit: status(0)
D/audio_hw_primary(  185): out_standby: exit
I/Icing.InternalIcingCorporaProvider( 3760): Updating corpora: A: MAYBE, C: FORCE_ALL
E/PowerHAL(  644): touch_boost: failed to send: No such file or directory
E/PowerHAL(  644): touch_boost: failed to send: No such file or directory
E/PowerHAL(  644): touch_boost: failed to send: No such file or directory
E/PowerHAL(  644): touch_boost: failed to send: No such file or directory
E/PowerHAL(  644): touch_boost: failed to send: No such file or directory
E/PowerHAL(  644): touch_boost: failed to send: No such file or directory
I/Process ( 8555): Sending signal. PID: 8555 SIG: 9
D/audio_hw_primary(  185): start_output_stream: enter: usecase(1: low-latency-playback) devices(0x2)
D/audio_hw_primary(  185): select_devices: out_snd_device(2: speaker) in_snd_device(0: none)
D/audio_hw_primary(  185): enable_snd_device: sending audio calibration for snd_device(2) acdb_id(14)
D/ACDB-LOADER(  185): ACDB -> send_afe_cal
D/audio_hw_primary(  185): enable_snd_device: snd_device(2: speaker)
I/WindowState(  644): WIN DEATH: Window{420cc9e8 u0 de.bricked.kcontrol/de.bricked.kcontrol.MainMenu}
I/ActivityManager(  644): Process de.bricked.kcontrol (pid 8555) has died.
W/ActivityManager(  644): Force removing ActivityRecord{428a13a0 u0 de.bricked.kcontrol/.MainMenu}: app died, no saved state
D/audio_hw_primary(  185): enable_audio_route: apply mixer path: low-latency-playback
D/audio_hw_primary(  185): start_output_stream: exit
D/su      ( 8736): child exited
D/su      ( 8737): client exited 0
W/InputMethodManagerService(  644): Got RemoteException sending setActive(false) notification to pid 8555 uid 10143
W/ActivityManager(  644): Permission denied: checkComponentPermission() owningUid=10063
W/ActivityManager(  644): Permission denied: checkComponentPermission() owningUid=10063
W/ActivityManager(  644): Permission denied: checkComponentPermission() owningUid=10063
W/ActivityManager(  644): Permission denied: checkComponentPermission() owningUid=10063
W/ActivityManager(  644): Permission denied: checkComponentPermission() owningUid=10063
W/ActivityManager(  644): Permission denied: checkComponentPermission() owningUid=10063
D/dalvikvm( 3760): GC_EXPLICIT freed 3841K, 70% free 3288K/10728K, paused 3ms+5ms, total 51ms
W/ActivityManager(  644): Permission denied: checkComponentPermission() owningUid=10063
W/ActivityManager(  644): Permission denied: checkComponentPermission() owningUid=10063
</pre>

Running: 

<pre>
root@mako:/ # uname -a
uname -a
uname -a
Linux localhost 3.4.0-bricked-mako-exp-g73fe91e #1 SMP PREEMPT Mon Aug 19 14:26:14 CEST 2013 armv7l GNU/Linux
</pre>

ROM: carbon-jb-nightly-20130912-0707, a 4.3 JSS15Q build. 

Regards,
Sylaan

**Comment by showp1984** [comment]
huh? Why don't I get that? Oo What did you do to your N4?
:D

**Comment by sylaan** [comment]
I did nothing! :) And I can make it crash quite consistent.

BTW, the github issue tracker sucks, I liked the one on google code better.

**Comment by sylaan** [comment]
There is nothing to be seen in dmesg

**Comment by showp1984** [comment]
It fails on is_lp(), which checks if there is a low power core present (and enabled currently), like the tegra3 has.
I am currently reworking the thermal settings with fragments and stats, but I will throw you a debug enabled test in an hour or so. :)
The issue tracker is not as good as google's, but still works fine for the purpose.

**Comment by showp1984** [comment]
Try this one:
[Link removed]

Should fix it.
Also has the new thermal stats, but that's WIP and everything closed is in there too.
(https://github.com/showp1984/KControl/issues?milestone=1&page=1&state=closed)

**Comment by sylaan** [comment]
Yep, it does not seem to crash anymore now. Good stuff :)

**Comment by showp1984** [comment]
Then I am closing down here.
Thank you for reporting! :)

**Comment by sylaan** [comment]
No problem.
